# coding: utf-8

"""
    Template web service

    This is a template of a web service

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from template_web_client.models.store_order_response import StoreOrderResponse

class TestStoreOrderResponse(unittest.TestCase):
    """StoreOrderResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StoreOrderResponse:
        """Test StoreOrderResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StoreOrderResponse`
        """
        model = StoreOrderResponse()
        if include_optional:
            return StoreOrderResponse(
                order_id = '',
                expires_in_seconds = 56
            )
        else:
            return StoreOrderResponse(
                order_id = '',
                expires_in_seconds = 56,
        )
        """

    def testStoreOrderResponse(self):
        """Test StoreOrderResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
