# coding: utf-8

"""
    Template web service

    This is a template of a web service

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from template_web_client.models.store_order_request import StoreOrderRequest

class TestStoreOrderRequest(unittest.TestCase):
    """StoreOrderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StoreOrderRequest:
        """Test StoreOrderRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StoreOrderRequest`
        """
        model = StoreOrderRequest()
        if include_optional:
            return StoreOrderRequest(
                data = {
                    'key' : null
                    }
            )
        else:
            return StoreOrderRequest(
                data = {
                    'key' : null
                    },
        )
        """

    def testStoreOrderRequest(self):
        """Test StoreOrderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
