# coding: utf-8

"""
    Template web service

    This is a template of a web service

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from template_web_client.api.orders_api import OrdersApi


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrdersApi()

    def tearDown(self) -> None:
        pass

    def test_retrieve_order_orders_order_id_get(self) -> None:
        """Test case for retrieve_order_orders_order_id_get

        Retrieve checkout order
        """
        pass

    def test_store_order_orders_post(self) -> None:
        """Test case for store_order_orders_post

        Store checkout order
        """
        pass


if __name__ == '__main__':
    unittest.main()
