# coding: utf-8

# flake8: noqa

"""
    Checkout service

    This is a checkout service for temporary storage of orders

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from template_web_client.api.orders_api import OrdersApi
from template_web_client.api.default_api import DefaultApi

# import ApiClient
from template_web_client.api_response import ApiResponse
from template_web_client.api_client import ApiClient
from template_web_client.configuration import Configuration
from template_web_client.exceptions import OpenApiException
from template_web_client.exceptions import ApiTypeError
from template_web_client.exceptions import ApiValueError
from template_web_client.exceptions import ApiKeyError
from template_web_client.exceptions import ApiAttributeError
from template_web_client.exceptions import ApiException

# import models into sdk package
from template_web_client.models.http_validation_error import HTTPValidationError
from template_web_client.models.health_check import HealthCheck
from template_web_client.models.retrieve_order_response import RetrieveOrderResponse
from template_web_client.models.store_order_request import StoreOrderRequest
from template_web_client.models.store_order_response import StoreOrderResponse
from template_web_client.models.validation_error import ValidationError
from template_web_client.models.validation_error_loc_inner import ValidationErrorLocInner
